name: Trigger a workflow to run when a pull request is merged 

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Pull request
      run: echo "Checking how pull request works."
